# Generated by Django 4.2.4 on 2024-01-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JPad', '0005_rename_username_debt_user_rename_username_todo_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='first_name',
        ),
    ]
